# Generated by Django 6.0.3 on 2026-04-08 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DonneesFondamentales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10, unique=True)),
                ("nom_societe", models.CharField(max_length=100)),
                ("secteur", models.CharField(max_length=50)),
                (
                    "benefice_net",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "actif_net",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                ("nb_actions", models.BigIntegerField(null=True)),
                (
                    "dividende",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("notation", models.CharField(blank=True, max_length=10)),
                ("mise_a_jour", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CoursHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("date", models.DateField()),
                (
                    "ouverture",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "plus_haut",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "plus_bas",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                ("cloture", models.DecimalField(decimal_places=2, max_digits=12)),
                ("volume", models.IntegerField(default=0)),
                (
                    "valeur",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "variation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "capitalisation",
                    models.DecimalField(decimal_places=2, max_digits=25, null=True),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("ticker", "date")},
            },
        ),
        migrations.CreateModel(
            name="SignalJournalier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("date", models.DateField(default=datetime.date.today)),
                ("cours", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rsi", models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                (
                    "mm20",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "mm50",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "boll_sup",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "boll_inf",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "vol_ratio",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "variation",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("per", models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ("pbr", models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ("dy", models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ("roe", models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                (
                    "per_secteur",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "pbr_secteur",
                    models.DecimalField(decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "dy_secteur",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "variation_secteur",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "perf_vs_secteur",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("score_fonda", models.IntegerField(default=0)),
                ("score_tech", models.IntegerField(default=0)),
                ("signal", models.CharField(default="NEUTRE", max_length=20)),
                ("interp_rsi", models.CharField(blank=True, max_length=200)),
                ("interp_mm", models.CharField(blank=True, max_length=200)),
                ("interp_boll", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-score_tech", "-score_fonda"],
                "unique_together": {("ticker", "date")},
            },
        ),
    ]
